name: Causica CI Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - uses: actions/cache@v3
      with:
        path: ~/.cache/uv
        key: ${{ hashFiles('uv.lock') }}
      id: cache

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        uv sync --extra seaborn --extra cpu
      if: steps.cache.outputs.cache-hit != 'true'

    - name: Verify pre-commit checks
      uses: pre-commit/action@v3.0.0
      with:
        extra_args: --all-files

    - name: Test with pytest
      run: uv run python -m pytest ./test
